RxTracker/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RxTracker.Data;
using RxTracker.Models;
using System.Linq;

namespace RxTracker.Controllers
{
    [Authorize]
    public class DoctorController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<MyUser> _userManager;

        public DoctorController(ApplicationDbContext context, UserManager<MyUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        /// <summary>
        /// This is the page for doing CRUD operations on doctors. The user is
        /// presented with a list of doctors. Selecting a doctor will display the
        /// editable details.
        /// </summary>
        /// <returns>A stream of html representing the web page</returns>
        public ActionResult Index()
        {
            // GET A REFERENCE TO THE USER
            var user = _userManager.FindByNameAsync(User.Identity.Name).Result;

            // GET A LIST OF ALL DOCTORS FOR THIS USER AND CREATE A LIST OF PERTINENT DETAILS
            var model = new ViewModels.Doctor.ListViewModel
            {
                DoctorList = _context.Doctor
                .Where(d => d.User == user)
                .Select(d => new ViewModels.Doctor.DoctorListItem
                {
                    DoctorId = d.DoctorId,
                    Hospital = d.Hospital,
                    Name = d.Name
                })
                .ToList()
            };

            return View(model);
        }

        /// <summary>
        /// Called by JavaScript to render the partial page which displays the details
        /// of the selected doctor. This partial page is inserted into the website.
        /// </summary>
        /// <param name="id">The primary key of the doctor for whom details are being
        /// requested. A check is made to make sure the current user is listed as the 
        /// user on this doctor's record.
        /// </param>
        /// <returns>A stream of html representing the partial page showing details.</returns>
        public ActionResult Details(int id)
        {
            // GET A REFERENCE TO THE USER
            var user = _userManager.FindByNameAsync(User.Identity.Name).Result;

            // FIND THE DOCTOR BY ID
            Doctor doctor = _context.Doctor.Find(id);

            // CONFIRM CURRENT USER HAS ACCESS TO THIS DOCTOR
            if (doctor != null && doctor.User != user)
            {
                return Unauthorized();
            }

            // IF DOCTOR NOT FOUND THEN RETURN AN EMPTY DOCTOR OBJECT
            // THIS WILL BE USED WHEN ADDING A NEW DOCTOR
            if (doctor == null)
            {
                doctor = new Doctor();
            }
            return PartialView("_DoctorPartial", doctor);
        }

        /// <summary>
        /// The details of a doctor are received from the front end and persisted into the
        /// database. If the DoctorId = 0, this indicates a new doctor is being added, otherwise
        /// we attempt to find the doctor by id and change his details to match the details received.
        /// So this method handles both create and update. Note the user associated with the 
        /// doctor is assigned by the backend and is not modified once assigned.
        /// </summary>
        /// <param name="doctor">The details received by the frontend mapped into a Doctor object</param>
        /// <returns>The id of the doctor added or edited or an error if the doctor could not be found
        /// or there is a database error
        /// </returns>
        [HttpPost]
        public ActionResult Edit([FromBody]Doctor doctor)
        {
            // GET A REFERENCE TO THE USER
            var user = _userManager.FindByNameAsync(User.Identity.Name).Result;

            // IF DOCTOR ID EQUALS ZERO THEN INSERT THE DOCTOR INTO THE DATABASE
            if (doctor.DoctorId == 0)
            {
                doctor.User = user;
                _context.Doctor.Add(doctor);
            }
            // ELSE CALL EditDoctor TO EDIT THE DOCTORS DETAILS
            else
            {
                EditDoctor(doctor, user);
            }

            // MAKE THE DATABASE INSERT OR UPDATE
            try
            {
                _context.SaveChanges();
            }
            catch (DbUpdateException)
            {
                return StatusCode(500);
                // TODO: Handle the error on the front end
            }

            return Json(doctor.DoctorId);
        }

        /// <summary>
        /// Receives a DoctorId from the front end. If the doctor is found first the
        /// user assigned to the doctor is compared to the current request to make sure
        /// they match. If the do the doctor is deleted from the database, otherwise
        /// an unauthorized reponse is returned.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete([FromBody]int id)
        {
            Doctor doctorToDelete = _context.Doctor.Find(id);
            if (doctorToDelete == null)
            {
                return NoContent();
            }

            // GET A REFERENCE TO THE USER
            var user = _userManager.FindByNameAsync(User.Identity.Name).Result;

            // CONFIRM THE CURRENT USER MATCHES THE USER ASSIGNED TO THIS DOCTOR
            if (doctorToDelete.User != user)
            {
                return Unauthorized();
                //TODO: Handle the unauthorized reponse 
            }

            // REMOVE THE DOCTOR FROM THE DATABASE
            _context.Doctor.Remove(doctorToDelete);

            // MAKE THE DATABASE CALL TO DELETE
            try
            {
                _context.SaveChanges();
            }
            catch (DbUpdateException)
            {
                return StatusCode(500);
                // TODO: Handle the error on the front end
            }

            return Ok();
        }


        /// <summary>
        /// Helper method to make controller logic clearer. Given a doctor and a user
        /// this method will find the doctor in the database, confirm the user
        /// has access to it and update the doctor. The call to update the database
        /// must be made separately.
        /// </summary>
        /// <param name="doctor">The information about the doctor to edit</param>
        /// <param name="user">The current request user trying to edit the doctor</param>
        /// <returns></returns>
        private bool EditDoctor(Doctor doctor, MyUser user)
        {
            // GET THE DOCTOR FROM THE DATABASE
            Doctor doctorToEdit = _context.Doctor.Find(doctor.DoctorId);

            // RETURN FALSE IF DOCTOR CANNOT BE FOUND OR USER REFERENCED
            // BY THIS DOCTOR DOES NOT MATCH THE PARAMETER
            if (doctorToEdit == null || doctorToEdit.User != user)
            {
                return false;
            }

            doctorToEdit.Name = doctor.Name;
            doctorToEdit.Hospital = doctor.Hospital;
            doctorToEdit.Address = doctor.Address;
            return true;
        }
    }
}

RxTracker/Controllers/DrugController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RxTracker.Data;
using RxTracker.Models;
using RxTracker.ViewModels;
using RxTracker.ViewModels.Drug;
using System.Linq;

namespace RxTracker.Controllers
{
    [Authorize]
    public class DrugController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<MyUser> _userManager;

        public DrugController(ApplicationDbContext context, UserManager<MyUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        /// <summary>
        /// The method queries the database to get a list of drugs associated 
        /// with this user. From here the user can intiate CRUD operations on
        /// their medications. It is called by the browser navigating to 
        /// https:// hostname /Drug. The list of drugs will appear on the left. 
        /// Selecting a specific drug will display the details on the right, from 
        /// which the user can update, insert and delete a drug.
        /// </summary>
        /// <returns>Html representing the web page</returns>
        public ActionResult Index()
        {
            // GET A REFERENCE TO THE USER
            var user = _userManager.FindByNameAsync(User.Identity.Name).Result;

            // QUERY THE DATABASE TO GET INFORMATION NEEDED FOR THE SUMMARY LIST
            ListViewModel model = new ListViewModel
            {
                DrugList = _context.Drug
                    .Where(d => d.User == user)
                    .Select(d => new DrugListItem
                    {
                        DrugId = d.DrugId,
                        DisplayName = d.DisplayName
                    })
                    .OrderBy(d => d.DisplayName)
                    .ToList()
            };

            // RETURN THE VIEW POPULATED WITH INFORMATION FROM THE DATABASE
            return View(model);
        }

        /// <summary>
        /// This method queries the database to find a specific drug based on the id.
        /// The details are returned as html and displayed on the web page. The drug
        /// must exist in the database and it must be associated with the user making
        /// this request. If the drug is not found, it is assumed the user is 
        /// requesting a blank form for entering a new drug.
        /// </summary>
        /// <param name="id">The DoctorId for which details are being requested</param>
        /// <returns>html representing a partial web page showing the details of a
        /// drug</returns>
        public ActionResult Details(int id)
        {
            // GET A REFERENCE TO THE USER
            var user = _userManager.FindByNameAsync(User.Identity.Name).Result;

            // FIND THE DRUG BY IT'S PRIMARY KEY
            Drug drug = _context.Drug.Find(id);

            // IF THE DRUG IS FOUND, BUT IS NOT ASSOCIATED WITH THIS USER, RETURN 401
            if (drug != null && drug.User != user)
            {
                return Unauthorized();
            }

            // IF THE DRUG IS NOT FOUND, RETURN A BLANK TEMPLATE FOR ENTERING A NEW DRUG
            if (drug == null)
            {
                drug = new Drug();
            }

            // IF THE DRUG IS FOUND, CREATE THE MODEL REQUIRED TO DISPLAY THE PAGE
            // THIS INCLUDES A LIST FOR THE 'GENERIC FOR' SELECT LIST.
            DetailViewModel model = new DetailViewModel
            {
                Drug = drug,
                GenericFor = _context.Drug
                    .Where(d => d.User == user && !string.IsNullOrEmpty(d.TradeName))
                    .Where(d => d.DrugId != drug.DrugId)
                    .Select(d => new SelectHelper
                    {
                        Value = d.DrugId,
                        Text = d.DisplayName
                    })
                    .OrderBy(d => d.Text)
                    .ToList()
            };

            // INSERT A BLANK RECORD FOR THE SELECT LIST
            model.GenericFor.Insert(0, new SelectHelper
            {
                Value = 0,
                Text = ""
            });

            // GENERATE AND RETURN THE HTML
            return PartialView("_DrugPartial", model);
        }

        /// <summary>
        /// This method will insert or update a drug based on the parameters received.
        /// If the DrugId = 0, this method will create a drug from the information received.
        /// If the DrugId != 0, this method will query the database to locate the drug,
        /// confirm it is associated with the current user and update the drug with the 
        /// information received.
        /// </summary>
        /// <param name="drug">The object containing the updated drug information</param>
        /// <returns>Redirects the user to the DrugList with the information updated</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Drug drug)
        {
            // IF THERE IS NO GENERIC, THE VALUE MUST BE SET TO NULL FOR THE DATABASE
            drug.GenericForId = drug.GenericForId == 0 ? null : drug.GenericForId;

            // GET A REFERENCE TO THE USER
            var user = _userManager.FindByNameAsync(User.Identity.Name).Result;

            // IF THE DrugId = 0, THEN WE ARE INSERTING A DRUG. THE CURRENT USERS ID
            // IS SAVED WITH THE DRUG.
            if (drug.DrugId == 0)
            {
                drug.User = user;
                _context.Drug.Add(drug);
            }
            // IF THE DrugId != 0 THEN WE ARE EDITING A DRUG. A SEPERATE METHOD
            // IS CALLED TO HANDLE THE EDIT AND RETURNS HERE TO UPDATE THE DATABASE
            else
            {
                EditDrug(drug, user);
            }

            // EXECUTE THE QUERY TO INSERT OR UPDATE THE DATABASE
            // ON ERROR REDIRECT THE USER TO THE ERROR PAGE
            try
            {
                _context.SaveChanges();
            }
            catch (DbUpdateException)
            {
                return View("Error");
            }

            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Method to handle the deleting of a Drug. This method is called from 
        /// JavaScript and, after confirming the drug is associated with the
        /// current user, will execute the delete statement.
        /// </summary>
        /// <param name="id">The DrugId of the drug to delete</param>
        /// <returns>Returns a 204 if the drug is not found, 401 if this drug
        /// is not associated with this user, 500 if there is an error while deleting
        /// or 200 if the drug is successfully deleted</returns>
        [HttpPost]
        public ActionResult Delete([FromBody]int id)
        {
            // QUERY THE DATABASE TO LOCATE THE DRUG TO DELETE
            Drug drugToDelete = _context.Drug.Find(id);

            // IF THE DRUG COULD NOT BE FOUND, RETURN 204
            if (drugToDelete == null)
            {
                return NoContent();
            }

            // GET A REFERENCE TO THE USER
            var user = _userManager.FindByNameAsync(User.Identity.Name).Result;

            // CONFIRM THE CURRENT USER MATCHES THE USER ASSIGNED TO THIS DOCTOR
            if (drugToDelete.User != user)
            {
                return Unauthorized();
                //TODO: Handle the unauthorized reponse 
            }

            // REMOVE THE DRUG FROM THE DATABASE
            _context.Drug.Remove(drugToDelete);

            // EXECUTE THE QUERY
            try
            {
                _context.SaveChanges();
            }
            catch (DbUpdateException)
            {
                return StatusCode(500);
            }

            // RETURN 200 IF SUCCESSFULLY DELETED
            return Ok();
        }

        /// <summary>
        /// Method to handled the updating of a drug. After confirming the drug is associated
        /// with the current user, the drug details are set to the passed in parameters and
        /// a boolean response is returned to the caller to indicate if the in memory
        /// version of the drug was successfully edited. This method does not persist the changes.
        /// The caller is required to do that.
        /// </summary>
        /// <param name="drug">The details of the drug to be edited</param>
        /// <param name="user">The user associated with this request</param>
        /// <returns>True if the drug was loaded into memory from the database and sucessfully edited,
        /// false otherwise
        /// </returns>
        private bool EditDrug(Drug drug, MyUser user)
        {
            // LOAD THE DRUG FROM THE DATABASE INTO MEMORY
            Drug drugToEdit = _context.Drug.Find(drug.DrugId);

            // CONFIRM THE DRUG WAS FOUND AND IS ASSOCIATED WITH THE CURRENT USER
            if (drugToEdit == null || drugToEdit.User != user)
            {
                return false;
            }

            // SET THE DRUG DETAILS TO THOSE IN THE PARAMETER
            drugToEdit.Name = drug.Name;
            drugToEdit.TradeName = drug.TradeName;
            drugToEdit.Manufacturer = drug.Manufacturer;
            drugToEdit.GenericForId = drug.GenericForId;
            return true;
        }
    }
}

RxTracker/Views/Shared/_DoctorPartial.cshtml
@model RxTracker.Models.Doctor

<form id="myForm" asp-action="Edit">
  <div asp-validation-summary="ModelOnly" class="text-danger"></div>
  <input type="hidden" asp-for="DoctorId" id="recordId" />

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text">Name</span>
    </div>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
  </div>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text">Hospital</span>
    </div>
    <input asp-for="Hospital" class="form-control" />
    <span asp-validation-for="Hospital" class="text-danger"></span>
  </div>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text">Address</span>
    </div>
    <input asp-for="Address" class="form-control" />
    <span asp-validation-for="Address" class="text-danger"></span>
  </div>

  <div class="form-group">
    <input type="button" id="btnSave" class="btn btn-primary" value="Save" />
    <button type="button" id="btnDelete" class="btn btn-danger">Delete</button>
  </div>
</form>

RxTracker/Views/Shared/_DrugPartial.cshtml
@model  RxTracker.ViewModels.Drug.DetailViewModel

<form asp-action="Edit">
  <div asp-validation-summary="ModelOnly" class="text-danger"></div>
  <input type="hidden" asp-for="Drug.DrugId" id="recordId" />

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text">Medication Name</span>
    </div>
    <input asp-for="Drug.Name" class="form-control" />
    <span asp-validation-for="Drug.Name" class="text-danger"></span>
  </div>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text">Brand Name</span>
    </div>
    <input asp-for="Drug.TradeName" class="form-control" />
    <span asp-validation-for="Drug.TradeName" class="text-danger"></span>
  </div>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text">Manufacturer</span>
    </div>
    <input asp-for="Drug.Manufacturer" class="form-control" />
    <span asp-validation-for="Drug.Manufacturer" class="text-danger"></span>
  </div>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1">Generic For</span>
    </div>
    <select asp-for="Drug.GenericForId" class="form-control" asp-items="@(new SelectList(Model.GenericFor, "Value", "Text"))"></select>
    <span asp-validation-for="Drug.GenericForId" class="text-danger"></span>
  </div>

  <div class="form-group">
    <input type="submit" id="btnSave" class="btn btn-primary" value="Save" />
    <button type="button" id="btnDelete" class="btn btn-danger">Delete</button>
  </div>
</form>

RxTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - RxTracker</title>

  <environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
  </environment>
  <environment exclude="Development">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
          crossorigin="anonymous"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
  </environment>
  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
      <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RxTracker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
          <partial name="_LoginPartial" />
          <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
              @if (User.Identity.IsAuthenticated)
              {
                <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Home</a>
              }
              else
              {
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
              }
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>
            @if (User.Identity.IsAuthenticated)
            {
              <li class="nav-item">
                <a class="nav-link my-dropdown-link" href="#">Functions &#x25BC;</a>
                <div class="my-dropdown">
                  <a asp-controller="Transaction" class="my-dropdown-item function-links">Enter the cost of a refill</a>
                  <a asp-controller="Prescription" class="my-dropdown-item function-links">Manage my prescriptions</a>
                  <a asp-controller="Statistics" class="my-dropdown-item function-links">View statistics on my prescriptions</a>
                  <a asp-controller="Drug" class="my-dropdown-item function-links">Manage the list of medications I take</a>
                  <a asp-controller="Doctor" class="my-dropdown-item function-links">Manage the list of doctors I see</a>
                  <a asp-controller="Pharmacy" class="my-dropdown-item function-links">Manage the list of pharmacies I visit</a>
                </div>
              </li>
            }
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <partial name="_CookieConsentPartial" />
  <div class="container main-content">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>

    <footer class="footer text-muted">
      <div class="container">
        &copy; 2019 - RxTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
      </div>
    </footer>
  </div>

  <environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
  </environment>
  <environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
    </script>
  </environment>
  <script src="~/js/site.js" asp-append-version="true"></script>

  @RenderSection("Scripts", required: false)
</body>
</html>

RxTracker/Views/Shared/_PharmacyPartial.cshtml
@model RxTracker.Models.Pharmacy

<form asp-action="Edit">
  <div asp-validation-summary="ModelOnly" class="text-danger"></div>
  <input type="hidden" asp-for="PharmacyId" id="recordId" />
  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text">Name</span>
    </div>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
  </div>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text">Address</span>
    </div>
    <input asp-for="Address" class="form-control" />
    <span asp-validation-for="Address" class="text-danger"></span>
  </div>
  <div class="form-group">
    <input type="submit" value="Save" class="btn btn-primary" />
    <button type="button" id="btnDelete" class="btn btn-danger">Delete</button>
  </div>
</form>

RxTracker/Views/Shared/_PrescriptionPartial.cshtml
@model EditViewModel

<form asp-action="Edit">
  <div asp-validation-summary="ModelOnly" class="text-danger"></div>
  <input type="hidden" asp-for="Prescription.PrescriptionId" id="recordId" />

  <div class="my-checkbox-group">
    <span>
      <input type="checkbox" id="Active" asp-for="Prescription.Active" />
      <label for="Active"></label>
    </span>
    <label for="Active">Active</label>
  </div>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1">Medication</span>
    </div>
    <select asp-for="Prescription.DrugId" class="form-control" asp-items="@(new SelectList(Model.Drugs, "Value", "Text"))"></select>
    <span asp-validation-for="Prescription.DrugId" class="text-danger"></span>
  </div>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1">Doctor</span>
    </div>
    <select asp-for="Prescription.DoctorId" class="form-control" asp-items="@(new SelectList(Model.Doctors, "Value", "Text"))"></select>
    <span asp-validation-for="Prescription.DoctorId" class="text-danger"></span>
  </div>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1">Form</span>
    </div>
    <input asp-for="Prescription.Form" class="form-control" />
    <span asp-validation-for="Prescription.Form" class="text-danger"></span>
  </div>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1">Dosage</span>
    </div>
    <input asp-for="Prescription.Dosage" class="form-control" />
    <span asp-validation-for="Prescription.Dosage" class="text-danger"></span>
  </div>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1">Regimen</span>
    </div>
    <input asp-for="Prescription.Regimen" class="form-control" />
    <span asp-validation-for="Prescription.Regimen" class="text-danger"></span>
  </div>

  <div class="form-group">
    <input type="submit" value="Save" class="btn btn-primary" />
    <button type="button" id="btnDelete" class="btn btn-danger">Delete</button>
  </div>
</form>

RxTracker/Views/Shared/_StatisticsPartial.cshtml
@model List<RxTracker.ViewModels.Statistics.Statistic>

<table class="table table-sm table-striped table-hover">
  <thead>
    <tr>
      <th>Medication</th>
      <th>Dosage</th>
      <th>Doctor</th>
      <th>Pharmacy</th>
      <th>Date</th>
      <th>Cost</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var transaction in Model)
    {
      <tr>
        <td>@transaction.DrugName</td>
        <td>@transaction.Dosage</td>
        <td>@transaction.DoctorName</td>
        <td>@transaction.PharmacyName</td>
        <td>@transaction.DateFilled</td>
        <td>@transaction.Cost</td>
      </tr>
    }
  </tbody>
</table>